#+TITLE: KNOWLEDGYN -- NOTAS VARIAS

* TESIS
** De acuerdo con [[http://en.wikipedia.org/wiki/Nicholas_Negroponte][Nicholas Negroponte]] (ver [[http://www.ted.com/talks/nicholas_negroponte_a_30_year_history_of_the_future][charla TED]]) en el futuro (30 años?) vamos a ingerir conocimiento en píldoras
* TEMAS
** aspectos socio-económicos y legales
*** KW va a tener que tener un costo, posiblemente muy alto
*** una posibilidad es que la controlen las grandes farmaceuticas o holdings con participación de farmaceuticas y universidades
*** otra posibilidad que no excluye la anterior es que meta mano el estado
*** al principio van a ser los yankees o los chinos los que tengan el breakthrough
**** posiblemente los chinos, por cuestiones estratégicas y de escrúpulos
**** el resto de los paises van a tener que seguirlos tipo carrera armamentística
**** qué pasaría con los emergentes?
- India
- Brasil
- México
- Rusia
- Argentina
**** qué pasaria con el tiempo cuando esto haya dejado de ser un factor determinante de poder?
*** sin duda habría grupos en desacuerdo con el uso de KW como herramienta de poder
- hackers
- derechos humanos
- filósofos
- sociólogos
- estudiantes universitarios
- sindicatos
- gente que "militó" en la década del '10 en el movimiento opencourse ware ([[http://en.wikipedia.org/wiki/OpenCourseWare][OCW]]) 
  - gente de coursera, de stanford, del mit
    - quienes son?
**** cuál sería la posición de Stallman, de Torvalds, de Gates?
**** cuál la de otros grandes académicos? empresarios? políticos? 
*** distintas ideologias tendrían distintas posturas
**** la izquierda querría la aplicación de KW para todo el mundo
**** la derecha le pondria precio y dejaría que la mano invisible del mercado se ocupara
**** los socialistas querrían garantizarla (al menos las primeras dosis)
*** alteraciones migratorias
**** algunos paises no tendrían esta tecnología
***** la gente se querría ir a los que la tuvieran
**** se profundizarían las tendencias migratorias actuales por razones económicas etc.
- lo gracioso sería pensar en el comienzo de esto, porque podría haber paises del
  primer mundo (o ex-primer mundo? EU del sur) que no tengan esto al principio.
  - españoles e italianos emigrando a China para la ingesta, replicando las
    corrientes migratorias argentinas de 150-200 años antes.

**** en los países nórdicos las haría el estado y las repartiría a todos los que tengan el pasaporte
***** habría una nueva presión migratoria para conseguir el KW
****** gente inmigrando
****** fronteras cerrándose para evitar presión en las arcas del Estado
****** leyes nuevas para ordenar la ingesta y garantizar el justo reparto

** aspectos técnicos
*** Negroponte dice que ingeriríamos una píldora
*** A mí me parece muy ficción cincuentera, lo veo más como una batería de tratamientos
- a lo mejor tendríamos que pensar en distintos tipos de tratamientos dependiendo del nivel de información que se quiere inocular
  - aprender a leer y escribir = una inyección, un poco de fiebre, riesgo casi nulo
  - aprender matemática/lengua/historia/geografía = un día internado (para cada cosa?)
  - recibirse de algo = tratamiento tipo quimio, de algunos meses
    - con consecuencias similares??
- sería interesante que mientras más contenido uno ingiere los efectos secundarios
  sean más fuertes, porque habría un efecto disuasorio que contrarrestaría el
  beneficio, agregandole sal al asunto (habría gente que no estaría dispuesta a ir
  tan lejos).
*** origen de la tecnología?
**** militar?
**** chinos?
**** IBM?! :p
*** aspectos científicos
*** cuál sería el timeline?
- siempre me perturbó un poco las pelis de ciencia ficción que ponen cosas extravagantes muy cerca...
- yo le daría 50 años para empezar a arrancar y otros 30 para afianzarse
** aspectos psicológicos y morales
*** mucho tiempo libre! se acabaría la escuela, la universidad?
*** imposible pensar en los chicos en casa...!
- como dice [[http://www.jennifersenior.com/journalism/][Jennifer Senior]] los chicos post-revolución industrial no tienen valor económico... Deberían volver a tenerlo? 
- tal vez la escuela se mantendría solo como buffer para que los padres puedan trabajar.
- tal vez los chicos tendrían otro papel, si pueden tener otras herramientas gracias
  a KW.
  - díficil que exista una involución en términos de trabajo infantil, pero tal vez
    los chicos puedan tener asignadas unas tareas que ayuden a la sociedad pero que
    no se considere trabajo.
  - una posibilidad de dudosa moralidad sería que sus juegos contuvieran realmente
    un crowdsourcing de algún tipo, como un mechanical turk infantil, que les dé un
    papel que substituya el de ser escolares.  
*** el tema del esfuerzo
**** hemos discutido dos aspectos
- el esfuerzo por conseguir el KW, ya que en principio podría costar, al menos en algunos países
- el no-esfuerzo de de repente tener esa información en la capocha, sin haber tenido que dedicarle el tiempo pre-KW 
**** pregunta: sería sostenible hacer una carrera de manera convencional (con la consecuente pérdida de tiempo).
- habría tal desventaja que puede que no: al recibirse uno, la gente con la misma
  edad que hayan ingerido KW tendrían algunos años ya de experiencia, haciendo muy
  difícil la competencia.
**** idea que mencionamos por ahí: que estudiar de manera convencional fuera más efectivo que con KW
- una opción es que esto sea así en los primeros años/décadas de implantación
- pero una vez que la tecnología avance, uno supondría que deje de ser así
*** algo de transformación social? 
- si pensamos que los jóvenes podrían trabajar (solo a partir de los 16-18 años por
  cuestiones morales), habría una transformación social en el sentido que se
  incorporaría una fuerza de trabajo muy joven que antes no estaba disponible tan
  temprano. 
- esto cambiaría (posiblemente equilibraría) las cuentas de muchos países, porque la
  gente pagaría seguro social más años.
- el perfil del desempleo podría cambiar bastante porque los jóvenes no tendrían que
  ser más la franja más susceptible al desempleo, ya que estarían ya formados
  (si tendrían menos experiencia, pero serían más baratos que gente más senior, con
  lo cual hay toda una dinámica que tener en cuenta).
- todo esto en la hipótesis de que el KW sea generalizado y no de elites.
  
** aspectos inusitados :)
* PUNTAS - 
** [[www.scientificamerican.com/article/what-do-great-musicians-have-in-common-dna/?&WT.mc_id%3DSA_WR_20140806][What Do Great Musicians Have in Common? DNA]]
** Sería interesante leer World War Z, que escuché que tiene una estructura interesante
** explorar KW como vacuna
